 /******************************************************************************
 *
 * Module: HC-SR04 Ultrasonic
 *
 * File Name: HC-SR04_Ultrasonic.h
 *
 * Description: Header file for the HC-SR04 Ultrasonic sensor driver
 *
 * Author: Hatem Essam
 *
 *******************************************************************************/

#ifndef HC_SR04_ULTRASONIC_H_
#define HC_SR04_ULTRASONIC_H_

#include "std_types.h"
/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define TR_PORT     PORTB_ID
#define TR_PIN      PIN5_ID
#define ECHO_PORT   PORTD_ID
#define ECHO_PIN    PIN6_ID



#define Min_Distance  2       /* 2 cm */
#define Max_Distance  400     /* 4 m */

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the HC-SR04 ULTRASONIC sensor:
 * 1. Setup the ICU call back function.
 * 2. Setup the direction for the trigger pin as output pin through the
 *    GPIO driver.
 */
 void Ultrasonic_init(void);
 /*
  * Description :
  * Send the Trigger pulse to the ultrasonic
  */
 void Ultrasonic_Trigger(void);
 /*
  * Description :
  * Send the trigger pulse by using Ultrasonic_Trigger function.
  * Start the measurements by the ICU from this moment.
  */
 uint16 Ultrasonic_readDistance(void);
 /*
  * Description :
  * This is the call back function called by the ICU driver.
  * This is used to calculate the high time (pulse time) generated by
  * the ultrasonic sensor.
  */
 void Ultrasonic_edgeProcessing(void);


#endif /* HC_SR04_ULTRASONIC_H_ */
