/******************************************************************************
 *
 * Module: HC-SR04 Ultrasonic
 *
 * File Name: HC-SR04_Ultrasonic.c
 *
 * Description: Source file for the HC-SR04 Ultrasonic sensor driver
 *
 * Author: Hatem Essam
 *
 *******************************************************************************/

#include "std_types.h"
#include <util/delay.h> /* For the delay functions */
#include "gpio.h"
#include "icu.h"
#include "HC-SR04_Ultrasonic.h"

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_timePeriod = 0;
uint16 g_timePeriodPlusHigh = 0;
uint32 g_dutyCycle = 0;


/*
 * Description :
 * Initialize the HC-SR04 ULTRASONIC sensor:
 * 1. Initialize the ICU driver as required.
 * 2. Setup the ICU call back function.
 * 3. Setup the direction for the trigger pin as output pin through the
 *    GPIO driver.
 */
void Ultrasonic_init(void){

	/* Create configuration structure for ICU driver */
	ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};

	/* Initialize the ICU driver */
	ICU_init(&ICU_Configurations);

	/* Set the Call back function pointer in the ICU driver */
	ICU_setCallBack(Ultrasonic_edgeProcessing);


	/*Setup the direction for the trigger pin as output pin*/
	GPIO_setupPinDirection(TR_PORT, TR_PIN, PIN_OUTPUT);
	/*Setup the direction for the ECHO pin as input pin*/
	GPIO_setupPinDirection(ECHO_PORT, ECHO_PIN, PIN_INPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void){

	GPIO_writePin(TR_PORT, TR_PIN, LOGIC_HIGH ); /*TR  -> PB5*/
	_delay_us(10); /* delay for not less than 10 micro second */
	GPIO_writePin(TR_PORT, TR_PIN, LOGIC_LOW ); /*TR  -> PB5*/
}

/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	uint16 distance;
	Ultrasonic_Trigger();

	if(g_edgeCount == 4)
	{
		g_edgeCount = 0;
		g_dutyCycle = ((float)(g_timePeriodPlusHigh-g_timePeriod) / (g_timePeriodPlusHigh - g_timeHigh));

	}
	distance = (g_dutyCycle *1700); /*Sound velocity = 340.00 m/s = 34000 cm/s
	                                The distance of Object (in cm) = (34000∗Time)/2 = 17000 * Time*/
	return distance;
}
/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){

	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}
	else if(g_edgeCount == 3)
	{
		/* Store the Period time value */
		g_timePeriod = ICU_getInputCaptureValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 4)
	{
		/* Store the Period time value + High time value */
		g_timePeriodPlusHigh = ICU_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		ICU_clearTimerValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);


		g_edgeCount=0;
		ICU_deInit();
	}

}
